version: '3.9'

services:
  musicat:
    build:
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN
      - BOT_CLIENT_ID
      - DB_CONNECTION_STRING=dbname=musicat host=db port=5432 user=musicat password=musicat
    # volumes:
    #   - ./:/root/musicat

  db:
    image: postgres:14.5-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: musicat
      POSTGRES_PASSWORD: musicat
      POSTGRES_DB: musicat
