version: '3.9'

services:
  musicat:
    image: shasha/musicat:latest
    build:
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    memswap_limit: 512M
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  db:
    image: postgres:14.5-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: musicat
      POSTGRES_PASSWORD: musicat
      POSTGRES_DB: musicat
    volumes:
      - /var/lib/postgres/data:/var/lib/postgres/data
